### ISSUE TITLE
Lowercase all querystring params

### ISSUE THREAD

**Issue by markstephens** [Financial-Times/spoor-enrichment#314]
I'm not 100% sure if this is a good idea or not, but it's the simplest from my PoV.

We get different cases of querystring parameter coming through. e.g. `segid` and `segID`

Can you lowercase them all? Can you think of any reasons not too?

In the URL annotation.

**Comment by chrisbrownuk** [comment]
Make sure it's just the query string parameter names and not the parameter values that get converted to lowercase.

**Comment by commuterjoy** [comment]
> Can you think of any reasons not too?

I read mixed advice about whether it matters, 

https://www.w3.org/TR/WD-html40-970708/htmlweb.html says assume case sensitivity 

... as does https://tools.ietf.org/html/rfc3986

And I wonder what happens to URL encoded parameters?

Perhaps we could just do a lower case and original version of the querystring?

**Comment by chrisbrownuk** [comment]
There are no additional problems caused by changing the case of URL
encoding. %2f is treated identically to %2F.

However, as I mentioned before,  I would recommend only lowercasing the
query parameter names and not the entire query string as some values can be
case sensitive.  (For example iJento used to pass a base64 encoded cookie
value in a query string, but also lowercased the query string.  This caused
them problems later when matching cookies.)


-- 

*Chris Brown*
TPO Web Analytics
Data Technology
Financial Times, One Southwark Bridge, London SE1 9HL

chris.brown@ft.com | +44 (0)207 873 4701

------------------------------

On 16 May 2016 at 22:43, Matt Chadburn <notifications@github.com> wrote:

> Can you think of any reasons not too?
>
> I read mixed advice about whether it matters,
>
> https://www.w3.org/TR/WD-html40-970708/htmlweb.html says assume case
> sensitivity
>
> ... as does https://tools.ietf.org/html/rfc3986
>
> And I wonder what happens to URL encoded parameters?
>
> Perhaps we could just do a lower case and original version of the
> querystring?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/spoor-enrichment/issues/314#issuecomment-219557586>
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by commuterjoy** [comment]
Yup, but the RFC says querystring as case sensitive, so I'm sure changing that isn't 100% good :)
